services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./crawlers/images:/app/images
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/client
    ports:
      - 8080:80
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongo-data: